### ISSUE TITLE
Setting initial scroll position

### ISSUE THREAD

**Issue by BillKeenan** [BwesShr/horizontal_calendar#2]
Hi,
looking at how to set the initial scroll position.

I want to init. with dates from -20 days to +20 days, but have it scrolled to the current date, any suggestion?

**Comment by BwesShr** [comment]
you can set initial date with (date-20) and the last date with (date+20) date with todays date parameters.

**Comment by BillKeenan** [comment]
Thanks for the reply , that doesn't seem to set the scroll position however, it always starts scrolled to the initial date, I'd like its ScrollController to be at day-0
