### ISSUE TITLE
Changing language problem

### ISSUE THREAD

**Issue by Vanhayten** [BwesShr/horizontal_calendar#5]
I need to show days in French, but the package is by default show days in English I change this line too 
`static String getDayOfWeek(DateTime date) => DateFormat('EEE', "fr").format(date);`
 But I don't need to edit package files

https://github.com/BwesShr/horizontal_calendar/blob/28f617d1ddc3d6a264410b6f64a98c22e69a2c93/lib/src/utils/date_parser.dart#L4

**Comment by BwesShr** [comment]
Fixed in version 1.1.1 
https://pub.dev/packages/horizontal_calendar
